config/routes.rb
RailsLocalAnalytics::Engine.routes.draw do
  get "/tracked_requests/:type", to: "dashboard#index", as: :tracked_requests
  get "/tracked_requests/:type/difference", to: "dashboard#difference", as: :difference_tracked_requests, constraints: {format: :json}

  root to: "application#root"
end

app/models/rails_local_analytics/application_record.rb
module RailsLocalAnalytics
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true

    scope :multi_search, ->(full_str){
      if full_str.present?
        relation = self

        full_str.split(' ').each do |str|
          like = connection.adapter_name.downcase.to_s == "postgres" ? "ILIKE" : "LIKE"

          sql_conditions = []

          display_columns.each do |col|
            sql_conditions << "(#{col} #{like} :search)"
          end

          relation = relation.where(sql_conditions.join(" OR "), search: "%#{sanitize_sql_like(str)}%")
        end

        next relation
      end
    }

    def self.display_columns
      column_names - ["id", "created_at", "updated_at", "total", "day"]
    end

  end
end

app/models/tracked_requests_by_day_page.rb
class TrackedRequestsByDayPage < RailsLocalAnalytics::ApplicationRecord
  self.table_name = "tracked_requests_by_day_page"

  before_create do
    self.total ||= 1
  end

end

app/models/tracked_requests_by_day_site.rb
class TrackedRequestsByDaySite < RailsLocalAnalytics::ApplicationRecord
  self.table_name = "tracked_requests_by_day_site"

  before_create do
    self.total ||= 1
  end
end

app/controllers/rails_local_analytics/application_controller.rb
module RailsLocalAnalytics
  class ApplicationController < ActionController::Base

    def root
      redirect_to tracked_requests_path(type: :page)
    end

  end
end

app/controllers/rails_local_analytics/dashboard_controller.rb
module RailsLocalAnalytics
  class DashboardController < ApplicationController
    PER_PAGE_LIMIT = 1000

    helper_method :pagination_page_number
    helper_method :display_columns

    def index
      params[:type] ||= "page"

      case params[:type]
      when "site"
        @klass = TrackedRequestsByDaySite
      when "page"
        @klass = TrackedRequestsByDayPage
      else
        head 404
        return
      end

      if params[:start_date].present?
        @start_date = Date.parse(params[:start_date])
      else
        @start_date = Date.today
      end

      if params[:end_date].present?
        @end_date = Date.parse(params[:end_date])
      else
        @end_date = Date.today
      end

      if @end_date < @start_date
        @end_date = @start_date
      end

      @results = fetch_records(@start_date, @end_date)

      if @results.size < PER_PAGE_LIMIT
        prev_start_date, prev_end_date = get_prev_dates(@start_date, @end_date)

        @prev_period_results = fetch_records(prev_start_date, prev_end_date)

        if @prev_period_results.size >= PER_PAGE_LIMIT
          @prev_period_results = nil
        end
      end
    end

    def difference
      case params.require(:type)
      when "site"
        @klass = TrackedRequestsByDaySite
      when "page"
        @klass = TrackedRequestsByDayPage
      end

      start_date = Date.parse(params.require(:start_date))
      end_date = Date.parse(params.require(:end_date))

      prev_start_date, prev_end_date = get_prev_dates(start_date, end_date)

      difference_where_conditions = params.require(:conditions).permit(*display_columns)

      current_total = fetch_records(
        start_date,
        end_date,
        difference_where_conditions: difference_where_conditions,
      ).first

      prev_total = fetch_records(
        prev_start_date,
        prev_end_date,
        difference_where_conditions: difference_where_conditions,
      ).first

      if prev_total
        diff = current_total - prev_total
      else
        diff = current_total
      end

      render json: {difference: diff}
    end

    private

    def fetch_records(start_date, end_date, difference_where_conditions: nil)
      aggregate_sql_field = "SUM(total)"

      tracked_requests = @klass
        .where("day >= ?", start_date)
        .where("day <= ?", end_date)
        .order("#{aggregate_sql_field} DESC")

      if difference_where_conditions
        tracked_requests = tracked_requests.where(difference_where_conditions)
      else
        tracked_requests = tracked_requests
          .limit(PER_PAGE_LIMIT)
          .offset(PER_PAGE_LIMIT * (pagination_page_number-1))

        if params[:filter].present?
          col, val = params[:filter].split("==")

          if display_columns.include?(col)
            tracked_requests = tracked_requests.where(col => val)
          else
            raise ArgumentError
          end
        end
      end

      if params[:search].present?
        tracked_requests = tracked_requests.multi_search(params[:search])
      end

      if params[:group_by].blank?
        pluck_columns = display_columns.dup
      else
        case params[:group_by]
        when "url_hostname_and_path"
          if display_columns.include?("url_hostname") && display_columns.include?("url_path")
            pluck_columns = [:url_hostname, :url_path]
          else
            raise ArgumentError
          end
        when "referrer_hostname_and_path"
          if display_columns.include?("referrer_hostname") && display_columns.include?("referrer_path")
            pluck_columns = [:referrer_hostname, :referrer_path]
          else
            raise ArgumentError
          end
        when *display_columns
          pluck_columns = [params[:group_by]]
        else
          raise ArgumentError
        end
      end

      group_by = pluck_columns.dup

      if difference_where_conditions
        pluck_columns = [aggregate_sql_field]
      else
        pluck_columns << aggregate_sql_field
      end

      tracked_requests
        .group(*group_by)
        .pluck(*pluck_columns)
    end

    def pagination_page_number
      page = params[:page].presence.to_i || 1
      page = 1 if page.zero?
      page
    end

    def get_prev_dates(start_date, end_date)
      if start_date == end_date
        prev_start_date = start_date - 1.day
        prev_end_date = prev_start_date
      else
        duration = end_date - start_date
        prev_start_date = start_date - duration
        prev_end_date = end_date - duration
      end
      return [prev_start_date, prev_end_date]
    end

    def display_columns
      @display_columns ||= @klass.display_columns
    end

  end
end

app/views/layouts/rails_local_analytics/_app_css.html.erb
<style>
  body{
    padding-bottom: 20px;
  }

  table td{
    overflow-wrap: anywhere;
  }

  input, select {
    border-radius: 5px;
    border: 1px solid #333;
    background: white;
    padding: 2px 5px;
  }

  button.is-link{
    border: none;
    background: none;
    color: #2780e3;
    text-decoration: underline;
    cursor: pointer;
  }
</style>

app/views/layouts/rails_local_analytics/application.html.erb
<% title = RailsLocalAnalytics.name.titleize %>

<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <meta name=viewport content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/cosmo/bootstrap.min.css" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= render "layouts/rails_local_analytics/app_css" %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to title , root_path, class: "navbar-brand" %>
        </h1>

        <ul class="nav navbar-nav navbar-right">
          <li class="<%= 'active' if params[:type] == "page" %>">
            <%= link_to "Requests By Page", tracked_requests_path(type: "page") %>
          </li>

          <li class="<%= 'active' if params[:type] == "site" %>">
            <%= link_to "Requests By Site", tracked_requests_path(type: "site") %>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container-fluid">
      <%= yield %>
    </main>
  </body>
</html>

app/views/rails_local_analytics/dashboard/index.html.erb
<%
  data_columns = params[:group_by].present? ? [params[:group_by]] : display_columns

  if data_columns.first == "url_hostname_and_path"
    data_columns = ["URL Hostname", "URL Path"]
  elsif data_columns.first == "referrer_hostname_and_path"
    data_columns = ["Referrer Hostname", "Referrer Path"]
  end
%>

<%
  group_by_opts = [
    ["All", nil],
  ]

  group_by_opts += display_columns.map{|x| [x.titleize.sub("Url ", "URL "), x] }

  if display_columns.include?("url_hostname") && display_columns.include?("url_path")
    index = group_by_opts.index(["URL Hostname", "url_hostname"])
    group_by_opts.insert(
      index,
      ["URL Hostname and Path", "url_hostname_and_path"],
    )
  end

  if display_columns.include?("referrer_hostname") && display_columns.include?("referrer_path")
    index = group_by_opts.index(["Referrer Hostname", "referrer_hostname"])
    group_by_opts.insert(
      index,
      ["Referrer Hostname and Path", "referrer_hostname_and_path"],
    )
  end
%>

<div class="well well-sm">
  <%= form_tag url_for(params.except(:start_date, :to).to_unsafe_hash), method: "get", id: "search-form" do %>
    <div>
      <label style="margin-right: 10px;">Group By: <%= select_tag :group_by, options_for_select(group_by_opts, params[:group_by]) %></label>

      <label style="margin-right: 10px;">From: <%= date_field_tag :start_date, @start_date %></label>
      <label style="margin-right: 10px;">To: <%= date_field_tag :end_date, @end_date %></label>

      <label style="margin-right: 10px;">Search: <%= text_field_tag :search, params[:search] %></label>
  <% end %>

  <% if params[:filter] %>
    <div>
      <label>Active Filter:</label>
      <div class="badge badge-primary" style="margin-top: 5px; margin-bottom: 10px;">
        <% filter_col, filter_val = params[:filter].split("==") %>
        <%= filter_col.titleize.sub("Url ", "URL ") %> = "<%= filter_val %>"
      </div>
      <%= link_to "Remove Filter", url_for(params.to_unsafe_h.merge(filter: nil)) %>
    </div>
  <% end %>

  <div>
    <%= link_to "Today", url_for(params.merge(start_date: Date.today, end_date: Date.today).to_unsafe_hash), style: ("font-weight: bold;" if @start_date == Date.today && @end_date == Date.today) %>
    |
    <% yesterday = Date.today - 1.day %>
    <%= link_to "Yesterday", url_for(params.merge(start_date: yesterday, end_date: yesterday).to_unsafe_hash), style: ("font-weight: bold;" if @start_date == yesterday && @end_date == yesterday) %>
    |
    <%= link_to "Last 7 days", url_for(params.merge(start_date: 7.days.ago.to_date, end_date: Date.today).to_unsafe_hash), style: ("font-weight: bold;" if @start_date == 7.days.ago.to_date && @end_date == Date.today) %>
    |
    <%= link_to "Last 30 days", url_for(params.merge(start_date: 30.days.ago.to_date, end_date: Date.today).to_unsafe_hash), style: ("font-weight: bold;" if @start_date == 30.days.ago.to_date && @end_date == Date.today) %>
    |
    <%= link_to "Last 3 Months", url_for(params.merge(start_date: 3.months.ago.to_date, end_date: Date.today).to_unsafe_hash), style: ("font-weight: bold;" if @start_date == 3.months.ago.to_date && @end_date == Date.today) %>
    |
    <%= link_to "Last 6 Months", url_for(params.merge(start_date: 6.months.ago.to_date, end_date: Date.today).to_unsafe_hash), style: ("font-weight: bold;" if @start_date == 6.months.ago.to_date && @end_date == Date.today) %>
    |
    <%= link_to "Last Year", url_for(params.merge(start_date: 1.year.ago.to_date, end_date: Date.today).to_unsafe_hash), style: ("font-weight: bold;" if @start_date == 1.year.ago.to_date && @end_date == Date.today) %>
  </div>
</div>

<h2>Requests by <%= params[:type].titleize %></h2>

<table class="table table-striped table-condensed">
  <thead>
    <% data_columns.each do |header| %>
      <th>
        <%= header.titleize.sub("Url ", "URL ") %>
      </th>
    <% end %>

    <th>
      Total
    </th>

    <th>
      Prev Period Difference
    </th>
  </thead>

  <tbody>
    <% @results.each_with_index do |row, row_index| %>
      <tr>
        <% row[0..-2].each_with_index do |value, col_index| %>
          <td>
            <% filter_param = "#{data_columns[col_index]}==#{value}" %>
            <%= link_to (value || ""), url_for(params.to_unsafe_h.merge(filter: filter_param)), title: "Filter" %>
          </td>
        <% end %>

        <td>
          <% total = row.last %>
          <%= number_with_delimiter(total) %>
        </td>

        <td>
          <% if @prev_period_results.nil? %>
            <%
              diff_params = {
                format: :json,
                type: params[:type],
                start_date: @start_date,
                end_date: @end_date,
                conditions: {},
              }

              data_columns.each_with_index do |col, col_index|
                diff_params[:conditions][col] = row[col_index]
              end

              placeholder_id = "diff-placeholder-#{row_index}"
            %>

            <button type="button" class="load-difference is-link" data-url="<%= difference_tracked_requests_path(diff_params) %>" data-placeholder-id="<%= placeholder_id %>">Load Difference</button>

            <div id="<%= placeholder_id %>"></div>
          <% else %>
            <% prev_period_row_index = @prev_period_results.index{|prev_period_row| row[0..-2] == prev_period_row[0..-2] } %>

            <% if prev_period_row_index.nil? %>
              +<%= number_with_delimiter(total) %>
            <% else %>
              <% prev_period_row = @prev_period_results.delete_at(prev_period_row_index) %>

              <% prev_period_total = prev_period_row.last %>
              <% diff = total - prev_period_total %>

              <% if diff >= 0 %>
                +<%= number_with_delimiter(diff) %>
              <% else %>
                <%= number_with_delimiter(diff) %>
              <% end %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div style="text-align: center;">
  <% if params[:page].present? && params[:page].to_i > 1 %>
    <%= link_to "Prev", url_for(params.to_unsafe_h.merge(page: pagination_page_number-1)) %>
    |
  <% end %>

  <% if @results.size >= RailsLocalAnalytics::DashboardController::PER_PAGE_LIMIT %>
    <%= link_to "Next", url_for(params.to_unsafe_h.merge(page: pagination_page_number+1)) %>
  <% end %>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function(){
    var form = document.querySelector("form#search-form")

    document.querySelectorAll("form#search-form select, form#search-form input").forEach(function(el){
      el.addEventListener("change", function(){
        form.submit();
      });
    });

    document.querySelectorAll("button.load-difference").forEach(function(el){
      el.addEventListener("click", async function(){
        el.disabled = true;

        var csrf_token = document.querySelector('meta[name="csrf-token"]').content;

        var request = new Request(
          el.getAttribute("data-url"),
          {
            method: "GET",
            headers: {
              "Content-Type": "application/json",
              Accept: "application/json",
              "X-CSRF-Token": csrf_token,
            },
          },
        );

        var response = await fetch(request)
          .then(function(response){
            response.json().then(function(parsed_response){
              el.style.display = "none";

              var placeholderEl = document.querySelector("#" + el.getAttribute("data-placeholder-id"));

              if(parsed_response.difference >= 1){
                placeholderEl.innerHTML = "+" + parsed_response.difference.toLocaleString();
              }else{
                placeholderEl.innerHTML = "" + parsed_response.difference.toLocaleString();
              }
            });

          });

      });
    });
  });
</script>